ALTER TABLE member
    ADD COLUMN country VARCHAR(255);

ALTER TABLE member
    MODIFY COLUMN nationality ENUM('RUSSIA', 'MONGOLIA', 'USA', 'VIETNAM', 'INDIA', 'INDONESIA', 'JAPAN', 'CHINA', 'THAILAND', 'PHILIPPINES', 'KOREAN_RUSSIAN', 'KOREAN_CHINESE', 'OTHER') NOT NULL;

ALTER TABLE member
    MODIFY COLUMN currency ENUM('USD', 'JPY', 'EUR', 'GBP', 'CAD', 'KRW', 'HKD', 'CNY', 'THB', 'IDR', 'VND', 'RUB', 'BDT');
